version: '3.7'

services:
#  web:
#    build:
#      args:
#        PLATFORM: ${PLATFORM:-linux/amd64}
#      context: .
#    image: vov-marketplace-web:local
#    command: sh -c "uvicorn main:app --reload"
#    volumes:
#      - ./static:/app/web/static
#      - ./media:/app/web/media
#      - .:/app/web/
#    expose:
#      - 8000
#    ports:
#      - 8000:8000
#    env_file:
#      - .env
#    depends_on:
#      - db

  db:
    image: mysql:8.0.33-debian
    platform: linux/x86_64
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/necessary_data.sql:/docker-entrypoint-initdb.d/2.sql
      - ./scripts/dev_data.sql:/docker-entrypoint-initdb.d/3.sql
    ports:
      - 3306:3306
    env_file:
      - .env.db
    environment:
      MYSQL_ROOT_HOST: '%'

volumes:
  mysql_data:
